#cloud-config

# include one or more SSH public keys
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA7K0hyVhiLTsS/BulHMLauH28MUQ3E30hW8W6LBu3pGNHEn3bqb4QcKZmfvjlE30HPwYodnvuC5zhGCN06mijWEraj2m/j8hISYJwjJHpUeIyw22mT4PSFREka9jSy+7k6yQrTSy0wTZp4VayWAdyUugwDlZ7NpDA1qpeJTvwVC5oEZVIwhwEMdMjf9K3YMJiYVevKaPKJbyKAaG11/KYmkEI/1JE4TZ/6iMU0qXcUf7K0S4229WcikAGQSz4cTPf6zfceDw8dlgISqNq6LiHKWTNDse+sIYaNljDg53lc7zardDFd79fNpab/gwzsG32/NtAQo5iINMTlznUJtEoaQ== rsa-key-20161003